# Generated by Django 4.0.1 on 2022-01-05 07:03

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=file.models.user_directory_path),
        ),
    ]
